from enum import Enum


class DefectClass(str, Enum):
    DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"
    WEBHOOK_INTEGRITY = "WEBHOOK_INTEGRITY"
    AMOUNT_CURRENCY = "AMOUNT_CURRENCY"
    SUSPICIOUS_CONTENT = "SUSPICIOUS_CONTENT"


class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class DetectorSource(str, Enum):
    STATIC = "STATIC"
    LLM = "LLM"
    BOTH = "BOTH"


class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    VERIFIED = "VERIFIED"
    NOT_REPRODUCED = "NOT_REPRODUCED"
    INCONCLUSIVE = "INCONCLUSIVE"
    BLOCKED = "BLOCKED"
    ERROR = "ERROR"


class EvidenceTier(str, Enum):
    EMULATED = "EMULATED"
    TEST_MODE = "TEST_MODE"


class FindingState(str, Enum):
    ADVISORY = "ADVISORY"
    QUEUED_FOR_VERIFICATION = "QUEUED_FOR_VERIFICATION"
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    EXCEPTION = "EXCEPTION"
    DISMISSED = "DISMISSED"


class ExposureKind(str, Enum):
    MEASURED = "MEASURED"
    ESTIMATED = "ESTIMATED"


class RemediationStatus(str, Enum):
    NONE = "NONE"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class RepositorySourceType(str, Enum):
    LOCAL_PATH = "LOCAL_PATH"
    GITHUB_HTTPS = "GITHUB_HTTPS"


class ScanState(str, Enum):
    INGEST = "INGEST"
    DISCOVER = "DISCOVER"
    STATIC = "STATIC"
    SEMANTIC = "SEMANTIC"
    NORMALIZE = "NORMALIZE"
    SCORE = "SCORE"
    SELECT_SCENARIOS = "SELECT_SCENARIOS"
    VERIFY = "VERIFY"
    DECIDE = "DECIDE"
    HUMAN_GATE = "HUMAN_GATE"
    REMEDIATE = "REMEDIATE"
    DONE = "DONE"
    FAILED = "FAILED"


class LLMStatus(str, Enum):
    OK = "OK"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"


class AnalysisStatus(str, Enum):
    OK = "OK"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    DONE = "DONE"
    FAILED = "FAILED"
    DEAD = "DEAD"


class AuditActor(str, Enum):
    SYSTEM = "SYSTEM"
    LLM = "LLM"
    VERIFIER = "VERIFIER"
    HUMAN = "HUMAN"


class AuditEventKind(str, Enum):
    SCAN_STARTED = "SCAN_STARTED"
    SCAN_FAILED = "SCAN_FAILED"
    DISCOVERY_COMPLETED = "DISCOVERY_COMPLETED"
    STATIC_ANALYSIS_COMPLETED = "STATIC_ANALYSIS_COMPLETED"
    LLM_ANALYSIS_COMPLETED = "LLM_ANALYSIS_COMPLETED"
    LLM_ANALYSIS_DEGRADED = "LLM_ANALYSIS_DEGRADED"
    FINDING_CREATED = "FINDING_CREATED"
    FINDING_STATE_CHANGED = "FINDING_STATE_CHANGED"
    VERIFICATION_REQUESTED = "VERIFICATION_REQUESTED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    REMEDIATION_PROPOSED = "REMEDIATION_PROPOSED"
    REMEDIATION_APPROVED = "REMEDIATION_APPROVED"
    REMEDIATION_REJECTED = "REMEDIATION_REJECTED"
    CHAOS_TOGGLED = "CHAOS_TOGGLED"
    CONFIG_LOADED = "CONFIG_LOADED"
